# Generated by Django 3.2.3 on 2021-06-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut de Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Cliente')),
                ('celular', models.IntegerField(verbose_name='Celular de Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo de Cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut de Empleado')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres de Empleado')),
                ('apaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno de Empleado')),
                ('amaterno', models.CharField(max_length=100, verbose_name='Apellido Materno de Empleado')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo de Empleado')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion de Empleado')),
                ('celular', models.IntegerField(verbose_name='Celular de Empleado')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut de Proveedor')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de Proveedor')),
                ('celular', models.IntegerField(verbose_name='Celular de Proveedor')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo de Proveedor')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.rubro')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['rut'],
            },
        ),
    ]
