# Generated by Django 3.2.3 on 2021-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.IntegerField(null=True, verbose_name='Usuario de Cliente'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.IntegerField(null=True, verbose_name='Usuario de Empleado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.IntegerField(null=True, verbose_name='Usuario de Proveedor'),
        ),
    ]
