# Generated by Django 3.2.3 on 2021-06-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Comedor',
            fields=[
                ('id_tipo_comedor', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Tipo Comedor')),
            ],
            options={
                'verbose_name': 'Comedor',
                'verbose_name_plural': 'Tipos de Comedor',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Plato')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripcion de Plato')),
                ('valor', models.IntegerField(verbose_name='Valor de Plato')),
                ('comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.tipo_comedor')),
            ],
            options={
                'verbose_name': 'Plato',
                'verbose_name_plural': 'Platos',
                'ordering': ['nombre'],
            },
        ),
    ]
