# Generated by Django 3.2.3 on 2021-06-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden_Pedido',
            fields=[
                ('num_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField(null=True, verbose_name='Fecha Emision Pedido')),
                ('fecha_recepcion', models.DateField(null=True, verbose_name='Fecha Recepcion Pedido')),
                ('estado', models.BooleanField(default=False, verbose_name='Enviado / No Envido')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion Pedido')),
            ],
            options={
                'verbose_name': 'Orden Pedido',
                'verbose_name_plural': 'Ordenes Pedidos',
                'ordering': ['num_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Producto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion de Producto')),
                ('valor', models.IntegerField(verbose_name='Valor de Producto')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('id_detalle_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Contidad de Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.orden_pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.producto')),
            ],
            options={
                'verbose_name': 'Detalle Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'ordering': ['pedido'],
            },
        ),
    ]
