# Generated by Django 3.2.3 on 2021-06-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0004_gasto_huesped_plato'),
        ('habitacion', '0001_initial'),
        ('comedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado_Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('celular', models.IntegerField(verbose_name='Celular')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.orden_compra')),
                ('tipo_comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.tipo_comedor')),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.tipo_habitacion')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['orden_compra'],
            },
        ),
    ]
