# Generated by Django 3.2.3 on 2021-06-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitacion', '0001_initial'),
        ('comedor', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('num_pago', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField(verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['num_pago'],
            },
        ),
        migrations.CreateModel(
            name='Orden_Compra',
            fields=[
                ('num_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio Reservacion')),
                ('fecha_termino', models.DateField(verbose_name='Fecha Termino Reservacion')),
                ('fecha_compra', models.DateField(auto_now_add=True, verbose_name='Fecha de compra Reservacion')),
                ('monto_total', models.IntegerField(null=True, verbose_name='Monto Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.pago')),
            ],
            options={
                'verbose_name': 'Ordene Compra',
                'verbose_name_plural': 'Ordenes de Compras',
                'ordering': ['num_compra'],
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id_huesped', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='Rut de Huesped')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres de Huesped')),
                ('apaterno', models.CharField(max_length=100, verbose_name='Apellido Paterno de Huesped')),
                ('amaterno', models.CharField(max_length=100, verbose_name='Apellido Materno de Huesped')),
                ('celular', models.IntegerField(verbose_name='Celular Huesped')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha ingreso')),
                ('fecha_salida', models.DateField(null=True, verbose_name='Fecha salida')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.habitacion')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.orden_compra')),
                ('tipo_comedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.tipo_comedor')),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
                'ordering': ['rut'],
            },
        ),
    ]
