# Generated by Django 3.2.3 on 2021-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_orden_compra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo / No activo'),
        ),
    ]
