# Generated by Django 3.2.3 on 2021-06-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comedor', '0001_initial'),
        ('compra', '0003_huesped_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto_Huesped_Plato',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_gasto', models.DateField(auto_now_add=True, verbose_name='Fecha de Consumo')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.huesped')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedor.plato')),
            ],
            options={
                'verbose_name': 'Gasto Cliente',
                'verbose_name_plural': 'Gastos del Huesped',
                'ordering': ['id_gasto'],
            },
        ),
    ]
